### ISSUE TITLE
The mod doesnt do anything any longer

### ISSUE THREAD

**Issue by farmboy0** [amazingalek/owml-light-bramble#13]
OWML version: 2.9.0
Mod version: 1.0.1
Game version: 1.1.13.456 (Steam)

The config menu is shown for the mod, all options are enabled
but its having no effect in game. Dark Bramble is in it original condition:
fog, fish and music.

**Comment by farmboy0** [comment]
The mod now requires _nebula.MenuFramework which isn't documented on the mod page nor the readme here then it works normally.

**Comment by sandsalamand** [comment]
@farmboy0 I can't reproduce this issue, OWML does not allow you to run the game with Light Bramble enabled if Menu Framework is disabled.

**Comment by farmboy0** [comment]
@sandsalamand OWML disables the mod, but it still shows the config for it

**Comment by sandsalamand** [comment]
@farmboy0 can you show a screenshot?

**Comment by farmboy0** [comment]
Will take a bit I'm playing in VR
