### ISSUE TITLE
Option to spawn Le Fishes

### ISSUE THREAD

**Issue by soldatami** [amazingalek/owml-light-bramble#15]
It would be pretty epic if you could add an option to select whether you want fishes or not to appear. This could be epic in combination with this mod: https://outerwildsmods.com/mods/customizableanglerfishai/

I don't know C# so I cannot do a lot to help with this. But I do know general programming languages so if I get an indication on what lines to change I can find my way to solve this issue. Just like in Outer Wilds.

Thanks for this mod!

**Comment by soldatami** [comment]
I just saw the configuration optino in the "mods" selector.
I am sorry for this, it did not work on my other computer but it does work on my laptop

Again thanks for this mod.

**Comment by sandsalamand** [comment]
No problem! 👍
